# Generated by Django 6.0.3 on 2026-09-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='voice_audio',
            field=models.FileField(blank=True, null=True, upload_to='issue_audio/'),
        ),
    ]
