# Generated by Django 6.0.3 on 2026-09-20 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('decision', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_traces', to='issues.issue')),
            ],
            options={
                'verbose_name': 'Agent Trace',
                'verbose_name_plural': 'Agent Traces',
                'ordering': ['-timestamp'],
            },
        ),
    ]
