# Generated by Django 6.0.3 on 2026-03-04 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(max_length=15, unique=True)),
                ('location_text', models.CharField(max_length=200)),
                ('ward', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('fill_level', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=500)),
                ('last_collected', models.DateTimeField()),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
